### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by xallonmex** [seantomburke/kbb-craigslist#32]
Any update to this plugin? It doesn't pull any data from kbb.

**Comment by seantomburke** [comment]
Haven’t tested it in a while, it doesn’t pull information for any car?

**Comment by xallonmex** [comment]
Nope, not at all.. Would be an awesome tool that a lot of people can benefit from.

**Comment by seantomburke** [comment]
Seems to be working, did you enter a zip code? Entering a zip code is required to get results

**Comment by xallonmex** [comment]
Still doesn’t work for some reason, here are some examples:

https://paste.pics/1187d2bbd968465c4b63ea9c6c78ad02
https://paste.pics/f3998570d3b6e7825223249288c107e6
https://paste.pics/2f31308c3991d3025465db5e936c6101
https://paste.pics/61bd9248527c3ec2d111d6d2ad390e67
https://paste.pics/30a3129d4e1e7847f9bd406b2879b7cc

Tried to clear my cache, still no luck. Also, with a zip code, no results. Not sure what the issue is exactly.


Thanks

**Comment by xallonmex** [comment]
Now it works, I appreciate your help Sean!

**Comment by xallonmex** [comment]
It’s just a got a few mini hiccups, sometimes it doesn’t want to pull the information and just says “Getting Price…”

**Comment by seantomburke** [comment]
With so many different types of cars on kbb and different posts by users on craigslist, it will never be perfect, but always room for improvement. It will be broken for some posts, but hopefully it provides enough value for most of the vehicles posted!

**Comment by xallonmex** [comment]
Good to know, I appreciate your help Sean!
